server:
  port: 9000
  shutdown: graceful # aguarda requests terminarem antes de matar o processo

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s # tempo máximo de espera
  application:
    name: api-gateway
  cloud:
    gateway:
      # configuração global de CORS
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "${FRONTEND_URI:http://localhost:5173}"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

      routes:
        # Rota para o User-Service
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/auth/**, /users/**
          filters:
            - name: TokenFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

        # Rota para o Profile-Service
        - id: profile-service-route
          uri: lb://profile-service
          predicates:
            - Path=/profile/**
          filters:
            - name: TokenFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

        # Rota para o Appointment-Service
        - id: appointment-service-route
          uri: lb://appointment-service
          predicates:
            - Path=/patient/**, /doctor/**, /appointments/**, /records/**, /prescriptions/**, /health-metrics/**, /documents/**, /adverse-effects/**, /admin/**
          filters:
            - name: TokenFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

        # Rota para o Pharmacy-Service
        - id: pharmacy-service-route
          uri: lb://pharmacy-service
          predicates:
            - Path=/pharmacy/**
          filters:
            - name: TokenFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

        # Rota para o Media-Service
        - id: media-service-route
          uri: lb://media-service
          predicates:
            - Path=/media/**
          filters:
            - name: TokenFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

        # Rota para o Chat WebSocket
        - id: chat-websocket-route
          uri: lb:ws://chat-service
          predicates:
            - Path=/chat/ws/**
          filters:
            - name: TokenFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
            - RewritePath=/chat/ws/(?<segment>.*), /ws/${segment}
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        # Rota para o Chat REST
        - id: chat-rest-route
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
          filters:
            - name: TokenFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

        # Rota para o Billing-Service
        - id: billing-service-route
          uri: lb://billing-service
          predicates:
            - Path=/billing/**
          filters:
            - name: TokenFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

        # Rota para o Audit-Service
        - id: audit-service-route
          uri: lb://audit-service
          predicates:
            - Path=/audit-logs/**
          filters:
            - name: TokenFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - name: TokenFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"